// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// UpdateURL is an autogenerated mock type for the UpdateURL type
type UpdateURL struct {
	mock.Mock
}

// UpdateURL provides a mock function with given fields: alias, newURL
func (_m *UpdateURL) UpdateURL(ctx context.Context, alias string, newURL string) (int64, error) {
	ret := _m.Called(ctx, alias, newURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, alias, newURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, alias, newURL)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, alias, newURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateURL creates a new instance of UpdateURL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateURL(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateURL {
	mock := &UpdateURL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
