// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// DeleteURL is an autogenerated mock type for the DeleteURL type
type DeleteURL struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: alias
func (_m *DeleteURL) DeleteURL(ctx context.Context, alias string) (int64, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeleteURL creates a new instance of DeleteURL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteURL(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteURL {
	mock := &DeleteURL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
